### PR TITLE
1.0.7

### PR DESCRIPTION
**Pull request by klinquist**

### CODE REVIEW

**Review by adriann0 — APPROVED** [review]

**Comment by adriann0** [comment]
I was just going to do that but you were faster :)

**Comment by klinquist** [comment]
> I was just going to do that but you were faster :)

You can do the `npm publish` :)

**Comment by adriann0** [comment]
@klinquist that's alright, go ahead and publish yourself

**Comment by klinquist** [comment]
> @klinquist that's alright, go ahead and publish yourself

Done!

**Pull request merged**
