### PR TITLE
Adding support for Base91 encoded telemetry.

### PR DESCRIPTION
**Pull request by TJCoffey**
I don't know if you're interested in it or not, but I took a shot at parsing out the compressed comment telemetry format that some trackers use. I've tried it with packets from my TinyTrak3, but that's all I've got access to.

### CODE REVIEW

**Comment by klinquist** [comment]
@TJCoffey  If you submit this PR to [my fork](https://github.com/klinquist/aprs-push-notification), I'll approve the PR and publish it (as aprs-parser2)

**Comment by adriann0** [comment]
@TJCoffey Thanks for the PR and sincere apologies for such delay. If you are still willing to contribute this - do I understand correctly that you are trying to implement [this](http://he.fi/doc/aprs-base91-comment-telemetry.txt) spec? I tried payloads from there and they didn't work.

**Comment by TJCoffey** [comment]
No worries on the delay. I just figured if I was adding the functionality, you might want it back in the main repo. I think that link is the correct spec. The only test data I had was from my own TinyTrak, so I haven't tried it on more generic messages with the different payload types from 3.11. Making this implementation more robust and adding unit tests has been on my todo list for a year now. If you don't want the current hack, I can resubmit when I clean it up.

**Comment by klinquist** [comment]
>  I can resubmit when I clean it up.

Yes please!

**Comment by TJCoffey** [comment]
I'm taking another dive into this and realized that adding the parsing to the MIC-E Position parser is incorrect. Trying to parse the strings from the he.fi documentation wasn't working for you because those are examples using uncompressed or compressed position formats. TinyTrak uses the MIC-E position format, so it was working on my device, but the compressed TM format works with all 3 position formats,  so breaking it out as its own separate parser will work better. I'm starting with a clean fork and will see what I can do. I'll open a new PR when I've got it correct.

**Pull request closed without merging**
